[package]
name = "optical-transfer-demo-qrstatic-wasm"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
qrstatic = { git = "https://github.com/ianzepp/qrstatic", rev = "301c2f0c165790f0981426dff1af830670f5d456" }
